version: '3.8'
services:
  postgres:
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=root
      - POSTGRES_DB=teste
    ports:
      - 5432:5432